### ISSUE TITLE
Doesn't seem to work with heroku

### ISSUE THREAD

**Issue by balupton** [emedvedev/slackin-extended#10]
```
-----> Node.js app detected
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NODE_VERBOSE=false
       NODE_ENV=production
       NODE_MODULES_CACHE=true
-----> Installing binaries
       engines.node (package.json):  ^8.0.0
       engines.npm (package.json):   unspecified (use default)
       
       Resolving node version ^8.0.0...
       Downloading and installing node 8.11.3...
       Using default npm version: 5.6.0
-----> Restoring cache
       Skipping cache restore (new-signature)
-----> Building dependencies
       Running heroku-prebuild
       
       > slackin-extended@1.1.9 heroku-prebuild /tmp/build_507a77a0924135f75c8c8242fa367025
       > npm install --only=dev
       
       
       > node-sass@4.9.0 install /tmp/build_507a77a0924135f75c8c8242fa367025/node_modules/node-sass
       > node scripts/install.js
       
module.js:549
    throw err;
    ^
Error: Cannot find module 'inherits'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/tmp/build_507a77a0924135f75c8c8242fa367025/node_modules/true-case-path/node_modules/glob/glob.js:46:16)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.9.0 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.9.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /tmp/npmcache.ksUCf/_logs/2018-07-22T23_39_04_677Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! slackin-extended@1.1.9 heroku-prebuild: `npm install --only=dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the slackin-extended@1.1.9 heroku-prebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /tmp/npmcache.ksUCf/_logs/2018-07-22T23_39_04_791Z-debug.log
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       If you're stuck, please submit a ticket so we can help:
       https://help.heroku.com/
       
       Love,
       Heroku
       
 !     Push rejected, failed to compile Node.js app.
 !     Push failed

```

**Comment by balupton** [comment]
Ended up shutting down my slack organisation as it seems slack is not the tool for public orgs. So nevermind!
