### ISSUE TITLE
Heroku app crash at launch

### ISSUE THREAD

**Issue by MariusMez** [emedvedev/slackin-extended#170]
Hi @emedvedev 

First of all, thanks for this updated fork :-)

I've tried to use it with the Heroku button, after settings all env var according to documentation. But the application keep crashing at start.

Here is the logs:

```
2020-03-10T10:34:47.403698+00:00 app[web.1]: > slackin-extended@2.0.0 start /app

2020-03-10T10:34:47.403698+00:00 app[web.1]: > cross-env-shell node ./bin/slackin $SLACK_SUBDOMAIN $SLACK_API_TOKEN --coc \"$SLACKIN_COC\" --channels \"$SLACKIN_CHANNELS\"

2020-03-10T10:34:47.403699+00:00 app[web.1]: 

2020-03-10T10:34:47.873923+00:00 app[web.1]: (node:31) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'status' of undefined

2020-03-10T10:34:47.873925+00:00 app[web.1]:     at SlackData.fetchUserCount (/app/lib/slack.js:89:30)

2020-03-10T10:34:47.873926+00:00 app[web.1]:     at process._tickCallback (internal/process/next_tick.js:68:7)

2020-03-10T10:34:47.874169+00:00 app[web.1]: (node:31) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

2020-03-10T10:34:47.874255+00:00 app[web.1]: (node:31) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

2020-03-10T10:34:47.877020+00:00 app[web.1]: /app/lib/slack.js:36

2020-03-10T10:34:47.877021+00:00 app[web.1]:         const { team } = res.body;

2020-03-10T10:34:47.877021+00:00 app[web.1]:                              ^

2020-03-10T10:34:47.877022+00:00 app[web.1]: 

2020-03-10T10:34:47.877022+00:00 app[web.1]: TypeError: Cannot read property 'body' of undefined

2020-03-10T10:34:47.877022+00:00 app[web.1]:     at request.get.query.end (/app/lib/slack.js:36:30)

2020-03-10T10:34:47.877023+00:00 app[web.1]:     at Request.callback (/app/node_modules/superagent/lib/node/index.js:728:3)

2020-03-10T10:34:47.877023+00:00 app[web.1]:     at ClientRequest.req.once.err (/app/node_modules/superagent/lib/node/index.js:647:10)

2020-03-10T10:34:47.877024+00:00 app[web.1]:     at Object.onceWrapper (events.js:286:20)

2020-03-10T10:34:47.877024+00:00 app[web.1]:     at ClientRequest.emit (events.js:198:13)

2020-03-10T10:34:47.877024+00:00 app[web.1]:     at TLSSocket.socketErrorListener (_http_client.js:401:9)

2020-03-10T10:34:47.877025+00:00 app[web.1]:     at TLSSocket.emit (events.js:198:13)

2020-03-10T10:34:47.877025+00:00 app[web.1]:     at emitErrorNT (internal/streams/destroy.js:91:8)

2020-03-10T10:34:47.877025+00:00 app[web.1]:     at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)

2020-03-10T10:34:47.877025+00:00 app[web.1]:     at process._tickCallback (internal/process/next_tick.js:63:19)

2020-03-10T10:34:47.886617+00:00 app[web.1]: npm ERR! code ELIFECYCLE

2020-03-10T10:34:47.887006+00:00 app[web.1]: npm ERR! errno 1

2020-03-10T10:34:47.888225+00:00 app[web.1]: npm ERR! slackin-extended@2.0.0 start: `cross-env-shell node ./bin/slackin $SLACK_SUBDOMAIN $SLACK_API_TOKEN --coc \"$SLACKIN_COC\" --channels \"$SLACKIN_CHANNELS\"`

2020-03-10T10:34:47.888331+00:00 app[web.1]: npm ERR! Exit status 1

2020-03-10T10:34:47.888535+00:00 app[web.1]: npm ERR! 

2020-03-10T10:34:47.888648+00:00 app[web.1]: npm ERR! Failed at the slackin-extended@2.0.0 start script.

2020-03-10T10:34:47.888748+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Don't know if I missed something or not ?

**Comment by MariusMez** [comment]
In fact I made a mistake setting the .env var SLACK_SUBDOMAIN (now its working fine)
