### ISSUE TITLE
Latest NPM package wasn't compiled before release

### ISSUE THREAD

**Issue by raysarebest** [emedvedev/slackin-extended#18]
When I download `slackin-extended` 1.1.10 via `npm install -g slackin-extended`, and I run the `slackin` command with my previously-working environment, I get the following error:

```
internal/modules/cjs/loader.js:775
    throw err;
    ^

Error: Cannot find module './../dist'
Require stack:
- /home/michael/.nvm/versions/node/v12.10.0/lib/node_modules/slackin-extended/bin/slackin
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:772:15)
    at Function.Module._load (internal/modules/cjs/loader.js:677:27)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/home/michael/.nvm/versions/node/v12.10.0/lib/node_modules/slackin-extended/bin/slackin:4:17)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:999:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/michael/.nvm/versions/node/v12.10.0/lib/node_modules/slackin-extended/bin/slackin'
  ]
}
```

The issue seems to stem from the `bin/slackin` file, where on line 4, it references a folder `./../dist` that doesn't seem to exist. Looking at the `gulpfile.babel.js`, it seems like this is supposed to be generated, but never was. I attempted to compile it myself, but it seems like the versions of gulp/babel that this project uses isn't compatible with node 12.10, so I couldn't. It be great if this project could be compiled, and then the compiled version uploaded as a new version on npm

**Comment by emedvedev** [comment]
Sorry for the delay! Update the gulp/babel dependencies and published the new version, so everything should be alright now.
