### ISSUE TITLE
Broken on now.sh?

### ISSUE THREAD

**Issue by GarySiu** [emedvedev/slackin-extended#4]
I've tried to install it through `now` as suggested. The original slackin worked fine and the deployment seems to have gone ok:

```
> Using Node.js 8.9.4 (requested: `^8.0.0`)
> Ready! https://slackin-extended-kazttitkgq.now.sh (copied to clipboard) [37s]
> Synced 1 file (1.74KB) [0ms]
> Initializing…
> Building
> ▲ npm install
> ⧗ Installing 28 main dependencies…
> ✓ Installed 865 modules [11s]
> ▲ npm run build
> > slackin-extended@1.1.2 build /home/nowuser/src
> > gulp
> [04:26:08] Failed to load external module @babel/register
> [04:26:08] Requiring external module babel-register
> [04:26:09] Using gulpfile ~/src/gulpfile.babel.js
> [04:26:09] Starting 'transpile'...
> [04:26:09] Starting 'assets'...
> [04:26:09] Starting 'sass'...
> [04:26:09] Finished 'assets' after 29 ms
> [04:26:09] Finished 'sass' after 30 ms
> [04:26:09] Finished 'transpile' after 494 ms
> [04:26:09] Starting 'default'...
> [04:26:09] Finished 'default' after 37 μs
> ▲ npm start
> > slackin-extended@1.1.2 start /home/nowuser/src
> > ./bin/slackin
> 2018-02-05T04:26:12.132Z slackin:main Theme: light
> 2018-02-05T04:26:12.141Z slackin:main Establishing connection with Slack
> 2018-02-05T04:26:12.182Z slackin:slack Fetching data from Slack
> 2018-02-05T04:26:12.215Z slackin:main Listening on 0.0.0.0:3000
> 2018-02-05T04:26:12.566Z slackin:slack Attempt failed, will retry
> Deployment complete!
```

However there seems to be a problem with the path?

```
Error: Failed to lookup view "main" in views directory "/home/nowuser/src/views"
    at Function.render (/home/nowuser/src/node_modules/express/lib/application.js:580:17)
    at ServerResponse.render (/home/nowuser/src/node_modules/express/lib/response.js:1008:7)
    at /home/nowuser/src/dist/index.js:192:29
    at Layer.handle [as handle_request] (/home/nowuser/src/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/nowuser/src/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/nowuser/src/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/nowuser/src/node_modules/express/lib/router/layer.js:95:5)
    at /home/nowuser/src/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/nowuser/src/node_modules/express/lib/router/index.js:335:12)
    at next (/home/nowuser/src/node_modules/express/lib/router/index.js:275:10)
```

demo url: https://slackin-extended-kazttitkgq.now.sh/

**Comment by emedvedev** [comment]
@GarySiu would you mind trying to deploy again? I've just pushed a new version: the `views/` directory wasn't indeed included in the Now configuration in `package.json`.

**Comment by sodabrew** [comment]
Still broken in slackin-extended 1.1.3 for me as well.

**Comment by sodabrew** [comment]
Thank you! This is exactly the change I made locally to get it working: 078bc979800941121a1da08ebe859883ee326490

Beat me to submitting a PR for the same. Hugely appreciated!

**Comment by emedvedev** [comment]
You're welcome :) Still broken on now.sh though, but should be fixed soon.

**Comment by sodabrew** [comment]
Yes, seems that `dist` is missing now in 1.1.4

**Comment by emedvedev** [comment]
Ugh, this is truly a Push Ugly Commits Straight to Master morning, but on the bright side, finally made it work now.sh. :)

Closing the issue. @GarySiu please try again, confirmed that it's working.

**Comment by GarySiu** [comment]
Tried with the update. Works great thanks!
